IV-4904 Initial commits of disable monitoring script
rightscale/rightlink_scripts pull request #109
Opened 2016-10-26 20:37 UTC by psschroeter

This downgrades an instance from Level 3 support (full capabilities) to Level 2 support by disabling monitoring. It can be run against any RightLink 5, 6 or 10 Server and must be run every boot.

2016-10-26 21:26 UTC, lopaka requested changes

2016-10-26 21:26 UTC, lopaka commented on rll-examples/disable-monitoring.sh
> +if which rightlink >/dev/null 2>&1; then
We do this `which rightlink >/dev/null` 3x - can we do it once and set it's existence to a variable - same way we do it with `sudo` and `retry_flags`?

2016-10-26 21:26 UTC, lopaka commented on rlw-examples/disable-monitoring.ps1
> +  exit 1
Do we want it to fail if monitoring is not detected?  I would think we would want to fail only if disabling of it has failed.  Can we just have it log as is stating monitoring not detect and `exit 0`?

2016-10-26 21:58 UTC, psschroeter commented on rll-examples/disable-monitoring.sh
> +if which rightlink >/dev/null 2>&1; then
sure, done

2016-10-26 22:01 UTC, psschroeter commented on rlw-examples/disable-monitoring.ps1
> +  exit 1
The error message was out of date. Updated to say that it couldn't find a RL 5, 6 or 10 installation so don't know how to proceed and exits with a error. This should only happen if I there's some script error because I missed some sort of test-case. Want to throw an error in this case so its gets reported back and the script can be improved.

2016-10-26 22:04 UTC, lopaka commented on rlw-examples/disable-monitoring.ps1
> +  exit 1
Ok, makes sense.

2016-10-26 22:06 UTC, lopaka approved these changes

2016-10-26 22:07 UTC, lopaka commented
LGTM

2016-10-26 22:16 UTC, merged

2016-10-27 23:36 UTC, douglaswth reviewed
Looks like one thing got through the initial review.

2016-10-27 23:36 UTC, douglaswth commented on rlw-examples/disable-monitoring.ps1
> +  if ($output -Match "enable_monitoring" -and $output -Match "false") {
It doesn't seem like this is correct.