Iv 4970 time sync
rightscale/rightlink_scripts pull request #113
Opened 2016-11-14 17:24 UTC by psschroeter

2016-11-14 19:46 UTC, lopaka requested changes

2016-11-14 19:46 UTC, lopaka commented on CHANGES.md
> +- Add setup-ntp.sh and setup-ntp.ps1 to Boot scripts. These scripts setup the NTP daemon to synchonize system time, by default to time.rightscale.com. Accurate time is important for monitoring and pr
typo: synchronize

2016-11-14 19:46 UTC, lopaka commented on rll/enable-monitoring.sh
> +    # Workaround for broken collectd
Do we want to add this change to the `CHANGES.md` file?

2016-11-14 21:30 UTC, psschroeter commented on rll/enable-monitoring.sh
> +    # Workaround for broken collectd
yup, added

2016-11-15 03:42 UTC, lopaka commented on rll/enable-monitoring.sh
> +    # Workaround for broken collectd
:+1:

2016-11-15 03:43 UTC, lopaka approved these changes

2016-11-15 03:44 UTC, lopaka commented
LGTM

2016-11-15 21:16 UTC, merged